import Head from "next/head";

import styles from "@/styles/Home.module.css";
import ArtistComp from "@/components/ArtistComp";

import artistsData from "@/data/artists.json";

export default function ArtistPage({ artist }) {
  return (
    <>
      <Head>
        <title>Artist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon_io/favicon.ico" />
      </Head>
      <div className={`${styles.page}`}>
        <main className={styles.main}>
          <ArtistComp artistData={artist} />
        </main>
      </div>
    </>
  );
}

// ----------------------------------------------------------------------
// USE getStaticPaths TO DEFINE SLUGS AT BUILD TIME
// ----------------------------------------------------------------------
export async function getStaticPaths() {
  // Generate a path object for every artist slug
  const paths = artistsData.map((artist) => ({
    params: { slug: artist.slug },
  }));

  return {
    paths,
    fallback: false, // If a user requests a path not defined here, show 404
  };
}

// ----------------------------------------------------------------------
// USE getStaticProps TO FETCH DATA FOR EACH SLUG AT BUILD TIME
// ----------------------------------------------------------------------
export async function getStaticProps({ params }) {
  // Look up the specific artist based on the slug from the path params
  const artist = artistsData.find((a) => a.slug === params.slug);

  if (!artist) {
    // This is mainly a safeguard, as getStaticPaths should prevent this
    return { notFound: true };
  }

  // Return the data as props
  return {
    props: {
      artist,
    },
  };
}
