import Head from "next/head";
import ArtistsComp from "@/components/ArtistsComp";

import styles from "@/styles/Home.module.css";

import artistsData from "@/data/artists.json";

export default function Artists({ artists }) {
  return (
    <>
      <Head>
        <title>Artists</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon_io/favicon.ico" />
      </Head>
      <div className={`${styles.page}`}>
        <main className={styles.main}>
          <ArtistsComp artists={artists} />
        </main>
      </div>
    </>
  );
}

export async function getStaticProps() {
  // Return the imported data as a prop named 'artists'
  // The imported artistsData is already the correct array format.
  return {
    props: {
      artists: artistsData.sort((a, b) => a.name.localeCompare(b.name)),
    },
    // Optional: Revalidate the page every 60 seconds in production
    // revalidate: 60,
  };
}
