import Head from "next/head";
import ArtistsComp from "@/components/ArtistsComp";

import styles from "@/styles/Home.module.css";

export default function Artists() {
  return (
    <>
      <Head>
        <title>Artists</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon_io/favicon.ico" />
      </Head>
      <div className={`${styles.page}`}>
        <main className={styles.main}>
          <ArtistsComp />
        </main>
      </div>
    </>
  );
}
