import Head from "next/head";
import Subscribe from "@/components/Subscribe";

import styles from "@/styles/Home.module.css";

export default function Cancel() {
  return (
    <>
      <Head>
        <title>Cancel Subscription</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon_io/favicon.ico" />
      </Head>
      <div className={`${styles.page}`}>
        <main className={styles.main}>
          <Subscribe />
        </main>
      </div>
    </>
  );
}
