import Head from "next/head";
import NavBar from "@/components/NavBar";
import Subscribe from "@/components/Subscribe";

import styles from "@/styles/Home.module.css";
import { Noto_Sans_JP } from "next/font/google";

const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["100", "400", "700", "900"],
  display: "swap",
});

export default function Cancel() {
  return (
    <>
      <Head>
        <title>MiHiFi - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.page} ${notoSansJP.className}`}>
        <NavBar />
        <main className={styles.main}>
          <Subscribe />
        </main>

        <footer className={styles.footer}></footer>
      </div>
    </>
  );
}
