import Head from "next/head";
import MusicPlayer from "@/components/MusicPlayer";
import { Noto_Sans_JP } from "next/font/google";
import styles from "@/styles/Home.module.css";
import NavBar from "@/components/NavBar";

const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["100", "400", "700", "900"],
  display: "swap",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Music Streamer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.page} ${notoSansJP.className}`}>
        <NavBar />
        <main className={styles.main}></main>

        <footer className={styles.footer}>
          <MusicPlayer />
        </footer>
      </div>
    </>
  );
}
