import Head from "next/head";

import styles from "@/styles/Home.module.css";
import ArtistComp from "@/components/ArtistComp";

export default function ArtistPage({ artistData }) {
  return (
    <>
      <Head>
        <title>{artistData.name} | Artist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon_io/favicon.ico" />
      </Head>
      <div className={`${styles.page}`}>
        <main className={styles.main}>
          <ArtistComp artistData={artistData} />
        </main>
      </div>
    </>
  );
}

export async function getServerSideProps(context) {
  const { slug } = context.params;

  const isDevelopment = process.env.NODE_ENV !== "production";
  const apiBaseUrl = isDevelopment
    ? "http://localhost:3000"
    : `https://${context.req.headers.host}`; // Use the host header for deployed env

  const response = await fetch(`${apiBaseUrl}/api/artists/${slug}`);

  if (response.status === 404) {
    return { notFound: true };
  }

  const artistData = await response.json();

  return {
    props: {
      artistData, // Pass the fetched data to the component as a prop
    },
  };
}
